version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mgnrega_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: mgnrega_backend
    restart: unless-stopped
    ports:
      - "5001:5000"    # CHANGED from 5000 to 5001
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/mgnrega
      - PORT=5000
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mgnrega_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001  # CHANGED to 5001
    depends_on:
      - backend

volumes:
  mongodb_data: